dteditor2/urls.py
from django.conf.urls import url
from . import views

app_name = 'dteditor2'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^img/(?P<path>.*)/$', views.ImgView.as_view(), name='img'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dteditor2.urls'))
]

dteditor2/forms.py
from django import forms


class EditorForm(forms.Form):

    # コード入力欄
    code = forms.CharField(
        widget=forms.HiddenInput,
        required=False,
    )

    # コマンド入力欄
    cmd = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
        })
    )

dteditor2/views.py
import base64

from django.http import Http404
from django.shortcuts import render
from django.views import generic

from .utils import editor


def home(request):
    """/ アクセスで呼び出されるビュー."""
    editor.update(request)  # エディタの更新
    context = {
        'editor': editor,
    }
    return render(request, 'dteditor2/home.html', context)


class ImgView(generic.TemplateView):
    """/img 画像ファイルクリックで呼び出されるビュー."""

    template_name = 'dteditor2/img.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        img_path = self.kwargs['path']
        try:
            src = open(img_path, 'rb').read()
        except FileNotFoundError:
            raise Http404('img Not Found')
        else:
            context['img_src'] = base64.b64encode(src)
            context['img_path'] = img_path
            return context

dteditor2/templates/dteditor2/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'dteditor2/bootstrap/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'dteditor2/css/base.css' %}">
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="{% static 'dteditor2/jquery/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'dteditor2/tether/tether.min.js' %}" ></script>
    <script src="{% static 'dteditor2/bootstrap/bootstrap.min.js' %}"></script>

    <!-- Ace Editor settings -->
    <script src="{% static 'dteditor2/ace/ace.js' %}"></script>
    <script src="{% static 'dteditor2/ace/ext-language_tools.js' %}"></script>
    <script>
        var langTools = ace.require("ace/ext/language_tools");
        var editor = ace.edit("code");
        var hidden_code =  $("#id_code");
        editor.getSession().setValue(hidden_code.val());
        editor.getSession().on('change', function(){
          hidden_code.val(editor.getSession().getValue());
        });
        editor.$blockScrolling = Infinity;
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true,
        });
        editor.setTheme("ace/theme/monokai");
        editor.getSession().setMode("ace/mode/{{ editor.file_type }}");
        editor.setFontSize(20);
    </script>

    <script>
        // 過去のコマンド履歴のリスト
        var commands = [
            {%  for cmd in editor.command.command_history %}
            "{{ cmd }}",
            {% endfor %}
            "",
        ];
        
        var now_index = commands.length - 1;

        window.onload = function () {
            
            // Bootstrap4 Tooltipsのアクティベート
            $('[data-toggle="tooltip"]').tooltip();
            
            // 出力エリアを一番↓までスクロール
            $('#output').animate({scrollTop: $('#output')[0].scrollHeight}, 0);
            
            // コマンド入力欄を空欄に初期化（フォームで束縛された値をけしてる）
            $('#id_cmd').val('');
            
            // コマンド入力欄にカーソルを。いちいち入力欄をクリックせずにすむ
            $('#id_cmd').focus();
            
            // ↑や↓キーで過去のコマンドを呼び出せる
            $('#id_cmd').keydown(function(e){
                switch(e.which){
                    case 38: // Key[↑]
                    now_index = now_index - 1;
                    if(now_index < 0){
                        now_index = 0;
                    }
                    cmd = commands[now_index];
                    $('#id_cmd').val(cmd);
                    break;
         
                    case 40: // Key[↓]
                    now_index = now_index + 1;
                    if(now_index >= commands.length){
                        now_index = commands.length - 1;
                    }
                    cmd = commands[now_index];
                    $('#id_cmd').val(cmd);
                    break;
                }
            });
        }
    </script>
  </body>
</html>


dteditor2/templates/dteditor2/home.html
{% extends "dteditor2/base.html" %}
{% load tagfilter %}
{% block title %}
  {{ editor.file_name }} - {{ editor.opening_file }}
{% endblock %}

{% block content %}


<nav class="navbar navbar-inverse bg-inverse py-1">
    <a class="navbar-brand" href="#">django-torina-editor2</a>
</nav>

<!-- ファイル選択とコード入力欄 -->
<div class="row" id="main-wrapper">
    
    <!-- ファイル選択エリア -->
    <div class="col-2 pt-1 scroll h-100">
        <div class="container-fluid">
            <p>Directory</p>
            {% for dir in editor.tree.dirs %}
                {{ dir.a_tag }}
            <hr>
            {% endfor %}
    
            <p>File</p>
            {% for file in editor.tree.files %}
                {{ file.a_tag }}
            <hr>
            {% endfor %}
        </div>
    </div>

    <!-- コード入力エリア -->
    <div class="col-7 pt-1">
        <div id="code" class="h-100"></div>
    </div>

    <!-- 設定等エリア -->
    <div class="col-3 pt-1 scroll">
        <ul class="nav nav-tabs" id="tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#settings" role="tab" aria-controls="settings">
                    Settings
                </a>
            </li>
        
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#origin-command" role="tab" aria-controls="origin-command">
                    Base Command
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#user-command" role="tab" aria-controls="user-command">
                    User Command
                </a>
            </li>
         
        </ul>
        <div class="tab-content pt-1 h-100" id="content">
            <div class="tab-pane active h-100" id="settings" role="tabpanel">
                <p>
                    <span class="text-muted">Opening File:</span><br>
                    {{ editor.opening_file }}
                </p>
                
                <p>
                    <span class="text-muted">Opening File Name</span><br>
                    {{ editor.file_name }}
                </p>
            
                <p>
                    <span class="text-muted">Ace Editor type:</span><br>
                    {{ editor.file_type }}
                </p>
            
                <p>
                    <span class="text-muted">Current Dir</span><br>
                    {{ editor.current_dir }}
                </p>

                <p>
                    <span class="text-muted">File Extension</span><br>
                    {{ editor.file_extension }}
                </p>

                <p>
                    <span class="text-muted">Sort Type</span><br>
                    {{ editor.tree.sort_type }}
                </p>

                <p>
                    <span class="text-muted">Sort Order</span><br>
                    {% if editor.tree.reverse %}
                        descending sequence
                    {% else %}
                        ascending order
                    {% endif %}
                </p>

                <p>
                    <span class="text-muted">Open Encoding</span><br>
                    {{ editor.open_encoding }}
                </p>

                <p>
                    <span class="text-muted">Save Encoding</span><br>
                    {{ editor.save_encoding }}
                </p>

                <p>
                    <span class="text-muted">Editor Python Path</span><br>
                    {{ editor.editor_python_path }}
                </p>

                <p>
                    <span class="text-muted">Editor Project Path</span><br>
                    {{ editor.editor_project_path }}
                </p>
            </div>
        
            <div class="tab-pane h-100" id="origin-command" role="tabpanel">
                {% for command in editor.command.base_command_list %}
                    <h3 class="font-italic">{{ command.0 }}</h3>
                    <p class="text-muted">{{ command.2 }}行目</p>
                    <pre>{{ command.1 }}</pre>
                <hr>
                {% endfor %}
            </div>

            <div class="tab-pane h-100" id="user-command" role="tabpanel">
                {% for command in editor.command.user_command_list %}
                    <h3 class="font-italic">{{ command.0 }}</h3>
                    <p class="text-muted">{{ command.2 }}行目</p>
                    <pre>{{ command.1 }}</pre>
                <hr>
                {% endfor %}
            </div>

        </div>

    </div>
</div>

<!-- 出力表示エリア -->
<div id="output-wrapper">
    <div id="cmd" class="container-fluid">
        <form action="{% url 'dteditor2:home' %}?opening_file={{ editor.opening_file }}&current_dir={{ editor.current_dir }}" method="POST" id="command-form">
            <input type="text" id="id_cmd" name="cmd" autocomplete="off">
            <input type="hidden" id="id_code" name="code" value="{{ editor.code }}">
            {% csrf_token %}
            <button type="submit" class="btn btn-info btn-sm">
                Send Command
            </button>
            
        </form>
    </div>
    
    
    <div id="output" class="bg-inverse scroll">
        <div class="container-fluid">
            {% for output in editor.command.output %}
            <span class="text-white">{{ output }}</span><br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}







dteditor2/templates/dteditor2/img.html
{% extends "dteditor2/base.html" %}
{% block title %}
  {{ img_path }}
{% endblock %}

{% block content %}
<img src="data:image/png;base64,{{ img_src }}">
{% endblock %}





